# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gGv0TdVU-kVyx12bSg6tIXJZZKXbGgWO
"""

!pwd

import os
from google.colab import drive
drive.mount('/content/drive')

ls

!nvidia-smi

cd /content/drive/MyDrive/

!git clone https://github.com/ultralytics/yolov5  # clone

cd yolov5

!pip install -r requirements.txt
!pip install --upgrade tensorflow

import torch
torch.__version__

!python train.py --data ../car/data.yaml --cfg yolov5s.yaml --weights 'yolov5s.pt' --batch-size 64

!python detect.py --weights runs/train/exp3/weights/best.pt --conf 0.5 --source test_night/images

import glob
from IPython.display import Image, display

for imageName in glob.glob('runs/detect/exp5/*.jpg'): #assuming JPG
    display(Image(filename=imageName))
    print("\n")